<Label>:
    color: 0, 0, 0, 1

<MainWidget>:
    Label:
        text: "Waiting for connection..."


<DeviceWidget>:
    name_label: name_label.__self__
    Label:
        id: name_label


<SensorWidget>:
    meaning_label: meaning_label.__self__
    value_label: value_label.__self__
    last_update_label: last_update_label.__self__
    Label:
        id: meaning_label
    Label:
        id: value_label
    Label:
        id: last_update_label